import {
  accessSync,
  chmodSync,
  constants,
  existsSync,
  mkdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { delimiter, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type ShimAgent = string;

const MANAGED_BEGIN = "# >>> ficta shims >>>";
const MANAGED_END = "# <<< ficta shims <<<";
const SHIM_MARKER = "Generated by ficta";
const LAUNCHER_NAME = ".ficta-launcher";
const LAUNCHER_MARKER = "FICTA_LAUNCHER=1";

export interface FindExecutableOptions {
  pathEnv?: string;
  excludeDirs?: readonly string[];
}

export interface InstallShimsOptions {
  home?: string;
  pathEnv?: string;
  shell?: string;
  rcPath?: string;
  nodePath?: string;
  fictaBin?: string;
  agents?: readonly string[];
  updateShell?: boolean;
  force?: boolean;
}

interface ShimWriteResult {
  agent: ShimAgent;
  path: string;
  status: "installed" | "unchanged" | "skipped-existing" | "skipped-launcher";
  realAgent?: string;
}

interface LauncherWriteResult {
  path: string;
  status: "installed" | "unchanged" | "skipped-existing";
}

interface LauncherRemoveResult {
  path: string;
  status: "removed" | "missing" | "skipped-not-ficta";
}

export interface InstallShimsResult {
  shimDir: string;
  rcPath?: string;
  pathUpdated: boolean;
  pathAlreadyConfigured: boolean;
  launcher: LauncherWriteResult;
  shims: ShimWriteResult[];
}

export interface UninstallShimsResult {
  shimDir: string;
  rcPath?: string;
  pathBlockRemoved: boolean;
  launcher: LauncherRemoveResult;
  shims: Array<{ agent: ShimAgent; path: string; status: "removed" | "missing" | "skipped-not-ficta" }>;
}

export function defaultFictaHome(home = homedir()): string {
  return join(home, ".ficta");
}

export function defaultShimDir(home = homedir()): string {
  return join(defaultFictaHome(home), "bin");
}

function defaultFictaBin(): string {
  // Source-tree/dev layout: src/install.ts -> ../bin/ficta.mjs.
  const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  return join(root, "bin", "ficta.mjs");
}

export function installShims(opts: InstallShimsOptions = {}): InstallShimsResult {
  const home = opts.home ?? homedir();
  const shimDir = defaultShimDir(home);
  const agents = opts.agents ?? [];
  const nodePath = opts.nodePath;
  const fictaBin = opts.fictaBin ?? defaultFictaBin();
  const pathEnv = opts.pathEnv ?? process.env.PATH ?? "";

  mkdirSync(shimDir, { recursive: true, mode: 0o700 });
  try {
    chmodSync(shimDir, 0o700);
  } catch {
    // Best-effort on filesystems that do not support POSIX modes.
  }

  const launcher = writeLauncher({ path: join(shimDir, LAUNCHER_NAME), nodePath, fictaBin, force: opts.force });
  const launcherAvailable = launcher.status !== "skipped-existing";

  const shims: ShimWriteResult[] = [];
  for (const agent of agents) {
    const shimPath = join(shimDir, agent);
    const existing = existsSync(shimPath) ? readFileSync(shimPath, "utf8") : undefined;
    const realAgent = findExecutable(agent, { pathEnv, excludeDirs: [shimDir] });

    if (existing !== undefined && !isFictaShim(existing) && !opts.force) {
      shims.push({ agent, path: shimPath, status: "skipped-existing", realAgent });
      continue;
    }
    if (!launcherAvailable) {
      shims.push({ agent, path: shimPath, status: "skipped-launcher", realAgent });
      continue;
    }

    const content = shimScript({ agent });
    const status = existing === content ? "unchanged" : "installed";
    if (status === "installed") writeFileSync(shimPath, content, { mode: 0o755 });
    chmodSync(shimPath, 0o755);
    shims.push({ agent, path: shimPath, status, realAgent });
  }

  let rcPath: string | undefined;
  let pathUpdated = false;
  let pathAlreadyConfigured = false;
  if (opts.updateShell !== false) {
    rcPath = opts.rcPath ?? shellRcPath(home, opts.shell ?? process.env.SHELL);
    const result = ensurePathBlock(rcPath, shimDir);
    pathUpdated = result.updated;
    pathAlreadyConfigured = result.alreadyConfigured;
  }

  return { shimDir, rcPath, pathUpdated, pathAlreadyConfigured, launcher, shims };
}

export function uninstallShims(
  opts: Pick<InstallShimsOptions, "home" | "rcPath" | "shell" | "agents" | "updateShell"> = {},
): UninstallShimsResult {
  const home = opts.home ?? homedir();
  const shimDir = defaultShimDir(home);
  const agents = opts.agents ?? [];
  const shims: UninstallShimsResult["shims"] = [];

  for (const agent of agents) {
    const shimPath = join(shimDir, agent);
    if (!existsSync(shimPath)) {
      shims.push({ agent, path: shimPath, status: "missing" });
      continue;
    }
    const content = readFileSync(shimPath, "utf8");
    if (!isFictaShim(content)) {
      shims.push({ agent, path: shimPath, status: "skipped-not-ficta" });
      continue;
    }
    unlinkSync(shimPath);
    shims.push({ agent, path: shimPath, status: "removed" });
  }

  const launcher = removeLauncher(join(shimDir, LAUNCHER_NAME));

  let rcPath: string | undefined;
  let pathBlockRemoved = false;
  if (opts.updateShell !== false) {
    rcPath = opts.rcPath ?? shellRcPath(home, opts.shell ?? process.env.SHELL);
    pathBlockRemoved = removePathBlock(rcPath);
  }

  return { shimDir, rcPath, pathBlockRemoved, launcher, shims };
}

export function findExecutable(command: string, opts: FindExecutableOptions = {}): string | undefined {
  const pathEnv = opts.pathEnv ?? process.env.PATH ?? "";
  const exclude = new Set((opts.excludeDirs ?? []).map((dir) => resolve(dir)));

  if (command.includes("/") && isExecutable(command)) return resolve(command);

  for (const dir of pathEnv.split(delimiter)) {
    if (!dir) continue;
    const resolvedDir = resolve(dir);
    if (exclude.has(resolvedDir)) continue;
    const candidate = join(dir, command);
    if (isExecutable(candidate)) return resolve(candidate);
  }
  return undefined;
}

function shellRcPath(home = homedir(), shell = process.env.SHELL): string {
  const base = shell?.split("/").pop() ?? "";
  if (base.includes("zsh")) return join(home, ".zshrc");
  if (base.includes("bash")) return join(home, ".bashrc");
  return join(home, ".profile");
}

function shimScript(args: { agent: string }): string {
  return `#!/bin/sh
# ${SHIM_MARKER}. Do not edit.
shim_dir=$(CDPATH= cd "$(dirname "$0")" && pwd) || exit 1
export FICTA_SHIM_AGENT=${shellQuote(args.agent)}
export FICTA_SHIM_DIR="$shim_dir"
exec "$shim_dir/${LAUNCHER_NAME}" ${shellQuote(args.agent)} "$@"
`;
}

function writeLauncher(args: {
  path: string;
  nodePath?: string;
  fictaBin: string;
  force?: boolean;
}): LauncherWriteResult {
  const existing = existsSync(args.path) ? readFileSync(args.path, "utf8") : undefined;
  if (existing !== undefined && !isFictaLauncher(existing) && !args.force) {
    return { path: args.path, status: "skipped-existing" };
  }

  const content = launcherScript({ nodePath: args.nodePath, fictaBin: args.fictaBin });
  const status = existing === content ? "unchanged" : "installed";
  if (status === "installed") writeFileSync(args.path, content, { mode: 0o755 });
  chmodSync(args.path, 0o755);
  return { path: args.path, status };
}

function removeLauncher(path: string): LauncherRemoveResult {
  if (!existsSync(path)) return { path, status: "missing" };
  const content = readFileSync(path, "utf8");
  if (!isFictaLauncher(content)) return { path, status: "skipped-not-ficta" };
  unlinkSync(path);
  return { path, status: "removed" };
}

function launcherScript(args: { nodePath?: string; fictaBin: string }): string {
  const nodeCommand = args.nodePath === undefined ? "/usr/bin/env node" : shellQuote(args.nodePath);
  return `#!/bin/sh
# ${SHIM_MARKER}. Do not edit.
# ${LAUNCHER_MARKER}
embedded_ficta=${shellQuote(args.fictaBin)}

valid_ficta_cli() {
  candidate=$1
  [ -f "$candidate" ] || return 1
  package_json=$(CDPATH= cd "$(dirname "$candidate")/.." 2>/dev/null && pwd)/package.json || return 1
  [ -f "$package_json" ] || return 1
  grep -Eq '"name"[[:space:]]*:[[:space:]]*"@serovaai/ficta"' "$package_json" 2>/dev/null
}

exec_ficta() {
  cli=$1
  shift
  exec ${nodeCommand} "$cli" "$@"
}

warn_stale_launcher() {
  cli=$1
  {
    echo "ficta: installed launcher points at a stale CLI path: $embedded_ficta"
    echo "ficta: using moved source checkout: $cli"
    echo "ficta: repair launcher with: pnpm --filter @serovaai/ficta ficta install --force"
  } >&2
}

try_moved_checkout() {
  root=$1
  shift
  [ -n "$root" ] || return 1
  candidate="$root/packages/ficta/bin/ficta.mjs"
  if valid_ficta_cli "$candidate"; then
    warn_stale_launcher "$candidate"
    exec_ficta "$candidate" "$@"
  fi
  return 1
}

if [ -n "$FICTA_CLI_PATH" ]; then
  if valid_ficta_cli "$FICTA_CLI_PATH"; then
    exec_ficta "$FICTA_CLI_PATH" "$@"
  fi
  echo "ficta: FICTA_CLI_PATH is set but is not a valid @serovaai/ficta CLI: $FICTA_CLI_PATH" >&2
  exit 127
fi

if valid_ficta_cli "$embedded_ficta"; then
  exec_ficta "$embedded_ficta" "$@"
fi

cwd=$(pwd 2>/dev/null || printf .)
git_root=$(git -C "$cwd" rev-parse --show-toplevel 2>/dev/null || true)
try_moved_checkout "$git_root" "$@"

search_dir=$cwd
while [ -n "$search_dir" ] && [ "$search_dir" != "/" ]; do
  try_moved_checkout "$search_dir" "$@"
  search_dir=$(dirname "$search_dir")
done

agent=\${1:-claude}
{
  echo "ficta: installed launcher could not find the ficta CLI:"
  echo "  $embedded_ficta"
  echo "ficta: repair from the moved checkout:"
  echo "  cd /path/to/ficta && pnpm --filter @serovaai/ficta ficta install --force"
  echo "ficta: or launch once with:"
  echo "  FICTA_CLI_PATH=/path/to/packages/ficta/bin/ficta.mjs $agent"
} >&2
exit 127
`;
}

function ensurePathBlock(rcPath: string, shimDir: string): { updated: boolean; alreadyConfigured: boolean } {
  const block = `${MANAGED_BEGIN}\nexport PATH="${shellDoubleQuote(shimDir)}:$PATH"\n${MANAGED_END}\n`;
  const before = existsSync(rcPath) ? readFileSync(rcPath, "utf8") : "";
  if (before.includes(MANAGED_BEGIN)) return { updated: false, alreadyConfigured: true };
  const prefix = before.length === 0 || before.endsWith("\n") ? "" : "\n";
  writeFileSync(rcPath, `${before}${prefix}${block}`, { mode: 0o600 });
  return { updated: true, alreadyConfigured: false };
}

function removePathBlock(rcPath: string): boolean {
  if (!existsSync(rcPath)) return false;
  let text = readFileSync(rcPath, "utf8");
  const before = text;
  for (;;) {
    const start = text.indexOf(MANAGED_BEGIN);
    if (start === -1) break;
    const end = text.indexOf(MANAGED_END, start);
    if (end === -1) break;
    const afterEnd = end + MANAGED_END.length;
    text = `${text.slice(0, start)}${text.slice(afterEnd).replace(/^\n/, "")}`;
  }
  if (text === before) return false;
  writeFileSync(rcPath, text, { mode: 0o600 });
  return true;
}

function isExecutable(path: string): boolean {
  try {
    accessSync(path, constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

function isFictaShim(content: string): boolean {
  return content.includes(SHIM_MARKER) && content.includes("FICTA_SHIM_AGENT");
}

function isFictaLauncher(content: string): boolean {
  return content.includes(SHIM_MARKER) && content.includes(LAUNCHER_MARKER);
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

function shellDoubleQuote(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll('"', '\\"').replaceAll("$", "\\$").replaceAll("`", "\\`");
}
