import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, join } from "node:path";
import { describe, expect, it } from "vitest";
import { defaultShimDir, findExecutable, installShims, uninstallShims } from "../src/install.js";

function tempDir(name: string): string {
  return mkdtempSync(join(tmpdir(), name));
}

function executable(path: string): void {
  writeFileSync(path, "#!/bin/sh\nexit 0\n", { mode: 0o755 });
  chmodSync(path, 0o755);
}

function fictaCheckout(root: string): string {
  const packageDir = join(root, "packages", "ficta");
  const binDir = join(packageDir, "bin");
  mkdirSync(binDir, { recursive: true });
  writeFileSync(join(packageDir, "package.json"), JSON.stringify({ name: "@steflsd/ficta" }));
  const cli = join(binDir, "ficta.mjs");
  writeFileSync(cli, "# ficta test cli\n");
  return cli;
}

function fakeNode(path: string, logPath: string): void {
  writeFileSync(
    path,
    `#!/bin/sh
printf '%s\\n' "$@" > ${shellQuote(logPath)}
exit 0
`,
    { mode: 0o755 },
  );
  chmodSync(path, 0o755);
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

describe("ficta shims", () => {
  it("installs agent-plugin shims and a managed PATH block", () => {
    const home = tempDir("ficta-home-");
    const realBin = tempDir("ficta-real-bin-");
    executable(join(realBin, "claude"));
    executable(join(realBin, "codex"));
    executable(join(realBin, "pi"));
    const rcPath = join(home, ".zshrc");

    const result = installShims({
      home,
      rcPath,
      pathEnv: realBin,
      nodePath: "/usr/bin/node",
      fictaBin: "/repo/bin/ficta.mjs",
      agents: ["claude", "codex", "pi"],
    });

    expect(result.launcher.status).toBe("installed");
    expect(result.shims.map((s) => s.status)).toEqual(["installed", "installed", "installed"]);
    expect(result.pathUpdated).toBe(true);
    const shimDir = defaultShimDir(home);
    const launcher = readFileSync(join(shimDir, ".ficta-launcher"), "utf8");
    const claudeShim = readFileSync(join(shimDir, "claude"), "utf8");
    expect(launcher).toContain("Generated by ficta");
    expect(launcher).toContain("FICTA_LAUNCHER=1");
    expect(launcher).toContain("/repo/bin/ficta.mjs");
    expect(launcher).toContain("valid_ficta_cli");
    expect(launcher).toContain("FICTA_CLI_PATH");
    expect(launcher).toContain("pnpm --filter @steflsd/ficta ficta install --force");
    expect(claudeShim).toContain("Generated by ficta");
    expect(claudeShim).toContain("FICTA_SHIM_AGENT='claude'");
    expect(claudeShim).toContain('exec "$shim_dir/.ficta-launcher" \'claude\' "$@"');
    expect(existsSync(join(shimDir, "ficta"))).toBe(false);
    expect(readFileSync(rcPath, "utf8")).toContain(`export PATH="${shimDir}:$PATH"`);
  });

  it("uses env node in the hidden launcher by default", () => {
    const home = tempDir("ficta-home-");

    installShims({
      home,
      updateShell: false,
      fictaBin: "/repo/bin/ficta.mjs",
      agents: ["pi"],
    });

    const shimDir = defaultShimDir(home);
    const launcher = readFileSync(join(shimDir, ".ficta-launcher"), "utf8");
    const piShim = readFileSync(join(shimDir, "pi"), "utf8");
    expect(launcher).toContain('exec /usr/bin/env node "$cli" "$@"');
    expect(piShim).not.toContain("/repo/bin/ficta.mjs");
  });

  it("launcher uses the embedded ficta CLI when it still exists", () => {
    const home = tempDir("ficta-home-");
    const checkout = tempDir("ficta-checkout-");
    const cli = fictaCheckout(checkout);
    const nodePath = join(tempDir("ficta-node-"), "node");
    const logPath = join(tempDir("ficta-log-"), "args.txt");
    fakeNode(nodePath, logPath);

    installShims({ home, updateShell: false, nodePath, fictaBin: cli, agents: ["claude"] });
    const launcher = join(defaultShimDir(home), ".ficta-launcher");
    const result = spawnSync(launcher, ["claude", "--version"], { encoding: "utf8" });

    expect(result.status).toBe(0);
    expect(result.stderr).toBe("");
    expect(readFileSync(logPath, "utf8").split("\n").filter(Boolean)).toEqual([cli, "claude", "--version"]);
  });

  it("launcher uses FICTA_CLI_PATH when the embedded source path moved", () => {
    const home = tempDir("ficta-home-");
    const checkout = tempDir("ficta-checkout-");
    const overrideCli = fictaCheckout(checkout);
    const nodePath = join(tempDir("ficta-node-"), "node");
    const logPath = join(tempDir("ficta-log-"), "args.txt");
    fakeNode(nodePath, logPath);

    installShims({ home, updateShell: false, nodePath, fictaBin: "/missing/ficta/bin/ficta.mjs", agents: ["claude"] });
    const launcher = join(defaultShimDir(home), ".ficta-launcher");
    const result = spawnSync(launcher, ["claude"], {
      encoding: "utf8",
      env: { ...process.env, FICTA_CLI_PATH: overrideCli },
    });

    expect(result.status).toBe(0);
    expect(result.stderr).toBe("");
    expect(readFileSync(logPath, "utf8").split("\n").filter(Boolean)).toEqual([overrideCli, "claude"]);
  });

  it("launcher discovers a moved checkout from the current repository root", () => {
    const home = tempDir("ficta-home-");
    const checkout = tempDir("ficta-checkout-");
    const movedCli = fictaCheckout(checkout);
    const nodePath = join(tempDir("ficta-node-"), "node");
    const logPath = join(tempDir("ficta-log-"), "args.txt");
    fakeNode(nodePath, logPath);

    installShims({ home, updateShell: false, nodePath, fictaBin: "/missing/ficta/bin/ficta.mjs", agents: ["codex"] });
    const launcher = join(defaultShimDir(home), ".ficta-launcher");
    const result = spawnSync(launcher, ["codex", "exec", "hello"], { cwd: checkout, encoding: "utf8" });

    expect(result.status).toBe(0);
    expect(result.stderr).toContain("installed launcher points at a stale CLI path");
    expect(result.stderr).toContain("pnpm --filter @steflsd/ficta ficta install --force");
    expect(readFileSync(logPath, "utf8").split("\n").filter(Boolean)).toEqual([
      realpathSync(movedCli),
      "codex",
      "exec",
      "hello",
    ]);
  });

  it("launcher fails with non-global repair guidance when no moved checkout is found", () => {
    const home = tempDir("ficta-home-");
    const outside = tempDir("ficta-outside-");
    const nodePath = join(tempDir("ficta-node-"), "node");
    const logPath = join(tempDir("ficta-log-"), "args.txt");
    fakeNode(nodePath, logPath);

    installShims({ home, updateShell: false, nodePath, fictaBin: "/missing/ficta/bin/ficta.mjs", agents: ["pi"] });
    const launcher = join(defaultShimDir(home), ".ficta-launcher");
    const result = spawnSync(launcher, ["pi"], { cwd: outside, encoding: "utf8" });

    expect(result.status).toBe(127);
    expect(result.stderr).toContain("/missing/ficta/bin/ficta.mjs");
    expect(result.stderr).toContain("cd /path/to/ficta && pnpm --filter @steflsd/ficta ficta install --force");
    expect(result.stderr).toContain("FICTA_CLI_PATH=/path/to/packages/ficta/bin/ficta.mjs pi");
    expect(existsSync(logPath)).toBe(false);
  });

  it("finds the real agent outside the shim dir", () => {
    const home = tempDir("ficta-home-");
    const shimDir = defaultShimDir(home);
    const realBin = tempDir("ficta-real-bin-");
    executable(join(realBin, "claude"));

    const result = findExecutable("claude", {
      pathEnv: [shimDir, realBin].join(delimiter),
      excludeDirs: [shimDir],
    });

    expect(result).toBe(join(realBin, "claude"));
  });

  it("uninstalls only ficta-owned shims and removes the managed PATH block", () => {
    const home = tempDir("ficta-home-");
    const rcPath = join(home, ".zshrc");
    installShims({
      home,
      rcPath,
      updateShell: true,
      nodePath: "/usr/bin/node",
      fictaBin: "/repo/bin/ficta.mjs",
      agents: ["claude", "codex", "pi"],
    });

    const result = uninstallShims({ home, rcPath, agents: ["claude", "codex", "pi"] });

    expect(result.launcher.status).toBe("removed");
    expect(result.shims.map((s) => s.status)).toEqual(["removed", "removed", "removed"]);
    expect(result.pathBlockRemoved).toBe(true);
    expect(existsSync(join(defaultShimDir(home), ".ficta-launcher"))).toBe(false);
    expect(existsSync(join(defaultShimDir(home), "ficta"))).toBe(false);
    expect(existsSync(join(defaultShimDir(home), "claude"))).toBe(false);
    expect(readFileSync(rcPath, "utf8")).not.toContain("ficta shims");
  });
});
