export {
  FICTA_CONFIG_PATH,
  FICTA_EGRESS_EVENT_HEADER,
  FICTA_EGRESS_PROOF_PATH,
  FICTA_PROTECTION_STATS_PATH,
  FICTA_REGISTRY_RELOAD_PATH,
  FICTA_REGISTRY_REVISION_HEADER,
  FICTA_TRACE_CAPTURE_PATH,
  FICTA_TRACE_CAPTURE_HEADER,
  FICTA_RESTORE_HIGHLIGHT_HEADER,
  FICTA_RESTORE_HIGHLIGHT_START,
  FICTA_RESTORE_HIGHLIGHT_END,
  FICTA_RESTORE_HIGHLIGHT_ORIGIN,
  FICTA_RESTORE_HIGHLIGHT_METADATA,
  FICTA_HEALTH_PATH,
  FICTA_PROTECTION_PREVIEW_PATH,
  FICTA_PROTECTION_TICKET_HEADER,
  FICTA_SCOPE_HEADER,
  FICTA_STATUS_PATH,
} from "@serovaai/ficta-protocol";
export { createFictaControlClient, type CreateFictaControlClientOptions, type FictaControlClient } from "./client.js";
export { fictaControlContract, type FictaControlContract } from "./contract.js";
export {
  decodeFictaControlError,
  encodeFictaControlError,
  fictaOperatorErrorData,
  fictaControlErrorData,
  fictaControlErrorStatus,
} from "./errors.js";
export {
  capabilitiesSchema,
  FICTA_CAPABILITIES_PATH,
  FICTA_CONTROL_CAPABILITIES,
  FICTA_CONTROL_PROTOCOL_VERSION,
  FICTA_SCOPE_MAX_LENGTH,
  healthSchema,
  PROTECTION_PREVIEW_TEXT_MAX_BYTES,
  PROTECTION_PREVIEW_VALUE_MAX,
  PROTECTION_PREVIEW_VALUES_MAX,
  PROTECTION_PREVIEW_VALUES_MAX_BYTES,
  protectionPreviewDetectorUnavailableErrorSchema,
  protectionPreviewErrorSchema,
  protectionPreviewFindingSchema,
  protectionPreviewForbiddenErrorSchema,
  protectionPreviewInputSchema,
  protectionPreviewInvalidRequestErrorSchema,
  protectionPreviewInvariantErrorSchema,
  protectionPreviewSchema,
  protectionTicketSchema,
  protectionStatusSchema,
  registryProtectionStatusSchema,
  type FictaCapabilities,
  type FictaHealth,
  type FictaProtectionPreview,
  type FictaProtectionPreviewError,
  type FictaProtectionPreviewInput,
  type FictaProtectionStatus,
} from "./schemas.js";

export * from "./extensions.js";
